### ISSUE TITLE
Uncaught Exception Error on Fresh Install

### ISSUE THREAD

**Issue by andrewmcodes** [npezza93/archipelago#41]
## Expected Behavior
Application to create .archipelago.json at the root directory, and then open.
## Actual Behavior
Application produced the following error, and did not render. After quitting the application and opening again, the .archipelago.json was created and the application loaded like normal. It looked like there was more to this error, but was unable to copy it as it extended past the initial fixed height Apple error modal.
``` javascript
Uncaught Exception: 
Error: ENOENT: no such file or directory, open '/Users/nighthawk/.archipelago.json'
    at Object.fs.openSync (fs.js:652:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at ConfigFile.contents (/Applications/Archipelago.app/Contents/Resources/app.asar/app/utils/config_file.coffee:30:19)
    at new ConfigFile (/Applications/Archipelago.app/Contents/Resources/app.asar/app/utils/config_file.coffee:21:21)
    at Object.<anonymous> (/Applications/Archipelago.app/Contents/Resources/app.asar/app/main/main.coffee:11:14)
    at Object.<anonymous> (/Applications/Archipelago.app/Contents/Resources/app.asar/app/main/main.coffee:1:1)
    at Object.<anonymous> (/Applications/Archipelago.app/Contents/Resources/app.asar/app/main/main.coffee:1:1)
    at Module._compile (module.js:569:30)
    at Object.loadFile (/Applications/Archipelago.app/Contents/Resources/app.asar/node_modules/coffeescript/lib/coffeescript/register.js:18:19)
    at Module.load (/Applications/Archipelago.app/Contents/Resources/app.asar/node_modules/coffeescript/lib/coffeescript/register.js:53:36)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Applications/Archipelago.app/Contents/Resources/app.asar/app/main/init.js:2:1)
    at Object.<anonymous> (/Applications/Archipelago.app/Contents/Resources/app.asar/app/main/init.js:4:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Object.<anonymous> (/Applications/Archipelago.app/Contents/Resources/electron.asar/browser/init.js:171:8)
    at Object.<anonymous> (/Applications/Archipelago.app/Contents/Resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3
```
## Steps to Reproduce
Delete .archipelago.json from root directory, and delete the application. Install a fresh copy from the link in the repo readme. Open the application

## OS Used
- [ ] Linux
- [x] Mac
- [ ] Windows

**Comment by npezza93** [comment]
Try downloading 2.0.0. This should now be resolved.
