### ISSUE TITLE
Add Official Windows Support

### ISSUE THREAD

**Issue by npezza93** [npezza93/archipelago#6]

**Comment by npezza93** [comment]
It'll build fine, but ill wait till after the release and the packages are out there to see how bad the damage is.

**Comment by techgurupezza** [comment]
@npezza93 When installing on windows it does not know where to put the default config and i do not see the settings tab in the menu

```text
Uncaught Error: %1 is not a valid Win32 application.
\\?\C:\Users\Christopher\AppData\Local\Temp\09856758-e287-4415-aa15-01cd8e92c115.tmp.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (C:\Program Files\Archipelago\resources\app.asar\node_modules\coffeescript\lib\coffeescript\register.js:53:36)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Program Files\Archipelago\resources\app.asar\node_modules\node-pty\lib\windowsPtyAgent.js:9:11)
    at Object.<anonymous> (C:\Program Files\Archipelago\resources\app.asar\node_modules\node-pty\lib\windowsPtyAgent.js:167:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (C:\Program Files\Archipelago\resources\app.asar\node_modules\coffeescript\lib\coffeescript\register.js:53:36)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Program Files\Archipelago\resources\app.asar\node_modules\node-pty\lib\windowsTerminal.js:18:25)
    at Object.<anonymous> (C:\Program Files\Archipelago\resources\app.asar\node_modules\node-pty\lib\windowsTerminal.js:182:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (C:\Program Files\Archipelago\resources\app.asar\node_modules\coffeescript\lib\coffeescript\register.js:53:36)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Program Files\Archipelago\resources\app.asar\node_modules\node-pty\lib\index.js:10:16)
    at Object.<anonymous> (C:\Program Files\Archipelago\resources\app.asar\node_modules\node-pty\lib\index.js:53:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (C:\Program Files\Archipelago\resources\app.asar\node_modules\coffeescript\lib\coffeescript\register.js:53:36)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Program Files\Archipelago\resources\app.asar\app\renderer\session.coffee:1:23)
    at Object.<anonymous> (C:\Program Files\Archipelago\resources\app.asar\app\renderer\session.coffee:1:1)
    at Object.<anonymous> (C:\Program Files\Archipelago\resources\app.asar\app\renderer\session.coffee:1:1)
    at Module._compile (module.js:569:30)
    at Object.loadFile (C:\Program Files\Archipelago\resources\app.asar\node_modules\coffeescript\lib\coffeescript\register.js:18:19)
    at Module.load (C:\Program Files\Archipelago\resources\app.asar\node_modules\coffeescript\lib\coffeescript\register.js:53:36)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Program Files\Archipelago\resources\app.asar\app\renderer\sessions.coffee:1:16)
    at Object.<anonymous> (C:\Program Files\Archipelago\resources\app.asar\app\renderer\sessions.coffee:1:1)
    at Object.<anonymous> (C:\Program Files\Archipelago\resources\app.asar\app\renderer\sessions.coffee:1:1)
    at Module._compile (module.js:569:30)
    at Object.loadFile (C:\Program Files\Archipelago\resources\app.asar\node_modules\coffeescript\lib\coffeescript\register.js:18:19)
    at Module.load (C:\Program Files\Archipelago\resources\app.asar\node_modules\coffeescript\lib\coffeescript\register.js:53:36)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Program Files\Archipelago\resources\app.asar\app\renderer\archipelago_app.coffee:4:24)
    at Object.<anonymous> (C:\Program Files\Archipelago\resources\app.asar\app\renderer\archipelago_app.coffee:1:1)
    at Object.<anonymous> (C:\Program Files\Archipelago\resources\app.asar\app\renderer\archipelago_app.coffee:1:1)
    at Module._compile (module.js:569:30)
    at Object.loadFile (C:\Program Files\Archipelago\resources\app.asar\node_modules\coffeescript\lib\coffeescript\register.js:18:19)
    at Module.load (C:\Program Files\Archipelago\resources\app.asar\node_modules\coffeescript\lib\coffeescript\register.js:53:36)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Program Files\Archipelago\resources\app.asar\app\renderer\renderer.coffee:5:23)
    at Object.<anonymous> (C:\Program Files\Archipelago\resources\app.asar\app\renderer\renderer.coffee:1:1)
    at Object.<anonymous> (C:\Program Files\Archipelago\resources\app.asar\app\renderer\renderer.coffee:1:1)
    at Module._compile (module.js:569:30)
    at Object.loadFile (C:\Program Files\Archipelago\resources\app.asar\node_modules\coffeescript\lib\coffeescript\register.js:18:19)
    at Module.load (C:\Program Files\Archipelago\resources\app.asar\node_modules\coffeescript\lib\coffeescript\register.js:53:36)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at file:///C:/Program%20Files/Archipelago/resources/app.asar/app/renderer/init.js:2:1
```
